CREATE TABLE public.deild (
    id SERIAL PRIMARY KEY,
    titill VARCHAR(256) NOT NULL,
    slug VARCHAR(256) NOT NULL,
    lysing TEXT,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.afangi (
    id SERIAL PRIMARY KEY,
    numer VARCHAR(16) NOT NULL,
    slugNumer VARCHAR(16) NOT NULL,
    heiti VARCHAR(256) NOT NULL,
    einingar VARCHAR(8) NOT NULL,
    kennslumisseri VARCHAR(64) NOT NULL,
    namstig VARCHAR(128) NOT NULL,
    hlekkur TEXT,
    deildId INTEGER NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT deildId FOREIGN KEY (deildId) REFERENCES deild (id) ON DELETE CASCADE
);