CREATE TABLE public.department (
    id SERIAL PRIMARY KEY,
    title VARCHAR(64) NOT NULL UNIQUE,
    slug VARCHAR(64) NOT NULL UNIQUE,
    description VARCHAR(1000) DEFAULT '',
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE semester as ENUM ('Vor', 'Sumar', 'Haust', 'Hálfsárs');

CREATE TABLE public.course (
    id SERIAL PRIMARY KEY,
    number VARCHAR(16) UNIQUE NOT NULL,
    title VARCHAR(128) UNIQUE NOT NULL,
    slug VARCHAR(128) UNIQUE NOT NULL,
    credits REAL NOT NULL CONSTRAINT credits_check CHECK (credits > 0),
    semester semester NOT NULL,
    level VARCHAR(128) NOT NULL,
    url VARCHAR(256),
    departmentid INTEGER NOT NULL,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT departmentid FOREIGN KEY (departmentid) REFERENCES department (id) ON DELETE CASCADE
);